name: Flask CI/CD Pipeline

on:
  push:
    branches: [master, staging]

permissions:
  contents: read

jobs:

# ---------------- CI ----------------
  ci:
    runs-on: ubuntu-latest
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pylint bandit

    - run: pylint app.py || true
    - run: bandit -r . -s B104,B101

    - run: pytest -v
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}


# ---------------- STAGING ----------------
  deploy-staging:
    needs: ci
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest

    steps:
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.STAGING_SSH_KEY }}

    - name: Deploy Staging
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.STAGING_USER }}@${{ secrets.STAGING_HOST }} << 'EOF'
        set -e

        APP_DIR="/var/www/flask-app"

        echo "🚀 Deploying Staging"

        sudo rm -rf "$APP_DIR"
        sudo mkdir -p "$APP_DIR"
        sudo chown -R $USER:$USER "$APP_DIR"

        cd "$APP_DIR"

        git clone https://github.com/Avinashsain/flask-ci-cd-app.git .

        echo "MONGO_URI=${MONGO_URI}" > .env

        sudo apt update
        sudo apt install -y python3-venv python3-pip

        python3 -m venv venv
        source venv/bin/activate

        pip install --upgrade pip
        pip install -r requirements.txt

        sudo systemctl restart flask-app

        echo "✅ Staging Done"
        EOF
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}


# ---------------- PRODUCTION ----------------
  deploy-production:
    needs: ci
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.PROD_SSH_KEY }}

    - name: Deploy Production
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }} << 'EOF'
        set -e

        APP_DIR="/var/www/flask-app"

        echo "🚀 Deploying Production"

        sudo rm -rf "$APP_DIR"
        sudo mkdir -p "$APP_DIR"
        sudo chown -R $USER:$USER "$APP_DIR"

        cd "$APP_DIR"

        git clone https://github.com/Avinashsain/flask-ci-cd-app.git .

        echo "MONGO_URI=${MONGO_URI}" > .env

        sudo apt update
        sudo apt install -y python3-venv python3-pip

        python3 -m venv venv
        source venv/bin/activate

        pip install --upgrade pip
        pip install -r requirements.txt

        sudo systemctl restart flask-app

        echo "✅ Production Done"
        EOF
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}