name: Flask CI/CD Pipeline

on:
  push:
    branches: [master, staging]
    tags:
      - "v*"
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:

  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Dev Tools
      run: |
        pip install pylint bandit pytest

    - name: Run Pylint
      run: pylint app.py || true

    - name: Run Bandit Security Scan
      run: bandit -r . -s B104,B101

    - name: Run Pytest
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: pytest -v


  deploy-staging:
    needs: ci
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Staging Server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.STAGING_USER }}@${{ secrets.STAGING_HOST }} "
          mkdir -p /var/www/flask-app &&
          cd /var/www/flask-app

          if [ ! -d .git ]; then
            git clone https://github.com/Avinashsain/flask-ci-cd-app.git .
          fi

          echo 'MONGO_URI=${{ secrets.MONGO_URI }}' > .env

          git fetch --all
          git reset --hard origin/staging

          pip3 install -r requirements.txt

          sudo systemctl restart flask-app
        "


  deploy-production:
    needs: ci
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Production Server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }} "
          mkdir -p /var/www/flask-app &&
          cd /var/www/flask-app

          if [ ! -d .git ]; then
            git clone https://github.com/Avinashsain/flask-ci-cd-app.git .
          fi

          echo 'MONGO_URI=${{ secrets.MONGO_URI }}' > .env

          git fetch --all
          git reset --hard origin/master

          pip3 install -r requirements.txt

          sudo systemctl restart flask-app
        "